'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class EasyTaskManager
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EasyTaskManager.EasyTaskManager", GetType(EasyTaskManager).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Easy Task Manager.
        '''</summary>
        Friend Shared ReadOnly Property ApplicationName() As String
            Get
                Return ResourceManager.GetString("ApplicationName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Priority Process.
        '''</summary>
        Friend Shared ReadOnly Property ChangePriorityProcess() As String
            Get
                Return ResourceManager.GetString("ChangePriorityProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close.
        '''</summary>
        Friend Shared ReadOnly Property Close() As String
            Get
                Return ResourceManager.GetString("Close", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CPU.
        '''</summary>
        Friend Shared ReadOnly Property CPU() As String
            Get
                Return ResourceManager.GetString("CPU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Create new task.
        '''</summary>
        Friend Shared ReadOnly Property CreateTask() As String
            Get
                Return ResourceManager.GetString("CreateTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property Description() As String
            Get
                Return ResourceManager.GetString("Description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a File.
        '''</summary>
        Friend Shared ReadOnly Property File() As String
            Get
                Return ResourceManager.GetString("File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finalize.
        '''</summary>
        Friend Shared ReadOnly Property Finalize() As String
            Get
                Return ResourceManager.GetString("Finalize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finalize Task.
        '''</summary>
        Friend Shared ReadOnly Property FinalizeTask() As String
            Get
                Return ResourceManager.GetString("FinalizeTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finalize Tree Services.
        '''</summary>
        Friend Shared ReadOnly Property FinalizeTreeProcess() As String
            Get
                Return ResourceManager.GetString("FinalizeTreeProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a General Information.
        '''</summary>
        Friend Shared ReadOnly Property GeneralInformation() As String
            Get
                Return ResourceManager.GetString("GeneralInformation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Go to Services.
        '''</summary>
        Friend Shared ReadOnly Property GotoServices() As String
            Get
                Return ResourceManager.GetString("GotoServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Type the name of the program, directory, document, or Internet resource you want to open with Windows.
        '''</summary>
        Friend Shared ReadOnly Property Head() As String
            Get
                Return ResourceManager.GetString("Head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a High.
        '''</summary>
        Friend Shared ReadOnly Property High() As String
            Get
                Return ResourceManager.GetString("High", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Idle.
        '''</summary>
        Friend Shared ReadOnly Property Idle() As String
            Get
                Return ResourceManager.GetString("Idle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Id Process.
        '''</summary>
        Friend Shared ReadOnly Property IdProcess() As String
            Get
                Return ResourceManager.GetString("IdProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Memory.
        '''</summary>
        Friend Shared ReadOnly Property Memory() As String
            Get
                Return ResourceManager.GetString("Memory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Process.
        '''</summary>
        Friend Shared ReadOnly Property NewProcess() As String
            Get
                Return ResourceManager.GetString("NewProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Services.
        '''</summary>
        Friend Shared ReadOnly Property NewServices() As String
            Get
                Return ResourceManager.GetString("NewServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Task.
        '''</summary>
        Friend Shared ReadOnly Property NewTask() As String
            Get
                Return ResourceManager.GetString("NewTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Normal.
        '''</summary>
        Friend Shared ReadOnly Property Normal() As String
            Get
                Return ResourceManager.GetString("Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ok.
        '''</summary>
        Friend Shared ReadOnly Property Ok() As String
            Get
                Return ResourceManager.GetString("Ok", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Open Process.
        '''</summary>
        Friend Shared ReadOnly Property OpenProcess() As String
            Get
                Return ResourceManager.GetString("OpenProcess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Priority.
        '''</summary>
        Friend Shared ReadOnly Property Priority() As String
            Get
                Return ResourceManager.GetString("Priority", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a High Priority.
        '''</summary>
        Friend Shared ReadOnly Property PriorityHigh() As String
            Get
                Return ResourceManager.GetString("PriorityHigh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Low Priority.
        '''</summary>
        Friend Shared ReadOnly Property PriorityLow() As String
            Get
                Return ResourceManager.GetString("PriorityLow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Priority Normal.
        '''</summary>
        Friend Shared ReadOnly Property PriorityNormal() As String
            Get
                Return ResourceManager.GetString("PriorityNormal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Process.
        '''</summary>
        Friend Shared ReadOnly Property Process() As String
            Get
                Return ResourceManager.GetString("Process", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Process Name.
        '''</summary>
        Friend Shared ReadOnly Property ProcessName() As String
            Get
                Return ResourceManager.GetString("ProcessName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Real Time.
        '''</summary>
        Friend Shared ReadOnly Property RealTime() As String
            Get
                Return ResourceManager.GetString("RealTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Running.
        '''</summary>
        Friend Shared ReadOnly Property Running() As String
            Get
                Return ResourceManager.GetString("Running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Service Name.
        '''</summary>
        Friend Shared ReadOnly Property ServiceName() As String
            Get
                Return ResourceManager.GetString("ServiceName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Services.
        '''</summary>
        Friend Shared ReadOnly Property Services() As String
            Get
                Return ResourceManager.GetString("Services", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start Services.
        '''</summary>
        Friend Shared ReadOnly Property StartServices() As String
            Get
                Return ResourceManager.GetString("StartServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Status.
        '''</summary>
        Friend Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Stopped.
        '''</summary>
        Friend Shared ReadOnly Property Stopped() As String
            Get
                Return ResourceManager.GetString("Stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Stop Services.
        '''</summary>
        Friend Shared ReadOnly Property StopServices() As String
            Get
                Return ResourceManager.GetString("StopServices", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sub Process.
        '''</summary>
        Friend Shared ReadOnly Property Subprocess() As String
            Get
                Return ResourceManager.GetString("Subprocess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Task.
        '''</summary>
        Friend Shared ReadOnly Property Task() As String
            Get
                Return ResourceManager.GetString("Task", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User Name.
        '''</summary>
        Friend Shared ReadOnly Property Username() As String
            Get
                Return ResourceManager.GetString("Username", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
